f:
  description: >-
    The optional f parameter indicates the output format which the server
    shall provide as part of the response document. It has preference over
    the HTTP Accept header. The default format is JSON.
  explode: false
  in: query
  name: f
  required: false
  schema:
    default: json
    enum:
      - json
      - html
    type: string
  style: form
sortby:
  description: >-
    The optional sortby parameter indicates the sort property and order on
    which the server shall present results in the response document using
    the convention `sortby=PROPERTY:X`, where `PROPERTY` is the sort
    property and `X` is the sort order (`A` is ascending, `D` is
    descending). Sorting by multiple properties is supported by providing a
    comma-separated list.
  explode: false
  in: query
  name: sortby
  required: false
  schema:
    type: string
  style: form
startindex:
  description: >-
    The optional startindex parameter indicates the index within the result
    set from which the server shall begin presenting results in the response
    document. The first element has an index of 0 (default).
  explode: false
  in: query
  name: startindex
  required: false
  schema:
    default: 0
    minimum: 0
    type: integer
  style: form
bbox:
  name: bbox
  in: query
  description: >-
    Only features that have a geometry that intersects the bounding box are selected.
    The bounding box is provided as four or six numbers, depending on whether the
    coordinate reference system includes a vertical axis (height or depth):

    * Lower left corner, coordinate axis 1
    * Lower left corner, coordinate axis 2
    * Minimum value, coordinate axis 3 (optional)
    * Upper right corner, coordinate axis 1
    * Upper right corner, coordinate axis 2
    * Maximum value, coordinate axis 3 (optional)

    The coordinate reference system of the values is WGS 84 longitude/latitude
    (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate
    reference system is specified in the parameter `bbox-crs`.

    For WGS 84 longitude/latitude the values are in most cases the sequence of
    minimum longitude, minimum latitude, maximum longitude and maximum latitude.
    However, in cases where the box spans the antimeridian the first value
    (west-most box edge) is larger than the third value (east-most box edge).

    If the vertical axis is included, the third and the sixth number are
    the bottom and the top of the 3-dimensional bounding box.

    If a feature has multiple spatial geometry properties, it is the decision of the
    server whether only a single spatial geometry property is used to determine
    the extent or all relevant geometries.
  required: false
  schema:
    type: array
    oneOf:
    - minItems: 4
      maxItems: 4
    - minItems: 6
      maxItems: 6
    items:
      type: number
  style: form
  explode: false
datetime:
  name: datetime
  in: query
  description: >-
    Either a date-time or an interval, open or closed. Date and time expressions
    adhere to RFC 3339. Open intervals are expressed using double-dots.

    Examples:

    * A date-time: "2018-02-12T23:20:50Z"
    * A closed interval: "2018-02-12T00:00:00Z/2018-03-18T12:31:12Z"
    * Open intervals: "2018-02-12T00:00:00Z/.." or "../2018-03-18T12:31:12Z"

    Only features that have a temporal property that intersects the value of
    `datetime` are selected.

    If a feature has multiple temporal properties, it is the decision of the
    server whether only a single temporal property is used to determine
    the extent or all relevant temporal properties.
  required: false
  schema:
    type: string
  style: form
  explode: false
limit:
  name: limit
  in: query
  description: >-
    The optional limit parameter limits the number of collections that are
    presented in the response document.

    Only items are counted that are on the first level of the collection in
    the response document. Nested objects contained within the explicitly
    requested items shall not be counted.

    * Minimum = 1
    * Maximum = 10000
    * Default = 10
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 10000
    default: 10
  style: form
  explode: false
